services:

  sqlserver:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest

    environment:
        SA_PASSWORD: "Senha123#"
        ACCEPT_EULA: "Y"
        MSSQL_PID: Developer
        MSSQL_TCP_PORT: "1433"

    ports:
      - "1433:1433"

    volumes:
      - db_data:/var/lib/mssqlql/data

volumes:
  db_data:
